name: Compiler tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t projetgl .

      - name: Run tests in Docker container
        run: |
          docker run --rm \
          --entrypoint /bin/bash \
          -v "${{ github.workspace }}:/home/gl/Projet_GL" \
          projetgl -c "cp -r /home/gl/Projet_GL /tmp/Projet_GL \
          && cd /tmp/Projet_GL \
          && mvn clean && mvn compile && mvn test"
