on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t projetgl .

      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/home/gl/Projet_GL" \
            projetgl /bin/bash -c "cd /home/gl/Projet_GL && mvn clean && mvn test"
